#!/bin/zsh -f
# sync-from-studio.sh — Pull development environment from Mac Studio to this MacBook
# Designed to run automatically via LaunchAgent or manually
# Uses absolute paths to avoid shell config / PATH issues on MacBook

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────
STUDIO_HOST="mac-primary"                     # SSH config alias (see ~/.ssh/config)
STUDIO_USER="YOUR_USERNAME"
HOME_NETWORK_PREFIX="192.168.1"            # Only sync when on this subnet
LOG_FILE="$HOME/Library/Logs/studio-sync.log"
SCRIPT_DIR="$(cd "$(/usr/bin/dirname "$0")" && /bin/pwd)"
EXCLUDE_FILE="$SCRIPT_DIR/sync-exclude.txt"
LOCK_FILE="/tmp/studio-sync.lock"

# ── Helpers ────────────────────────────────────────────────────
log() { /bin/echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"; }

notify() {
    /usr/bin/osascript -e "display notification \"$1\" with title \"Studio Sync\"" 2>/dev/null || true
}

# Count non-empty lines from rsync --itemize-changes output.
# Empty string → 0; otherwise wc -l of the captured stdout.
count_changes() {
    if [ -n "$1" ]; then
        /bin/echo "$1" | /usr/bin/wc -l | /usr/bin/tr -d ' '
    else
        /bin/echo 0
    fi
}

# Counters used throughout the run; initialized here so Phase 0 (reverse) can update them.
SYNC_ERRORS=0
CHANGES=0

cleanup() {
    /bin/rm -f "$LOCK_FILE"
}
trap cleanup EXIT

# ── Preflight checks ──────────────────────────────────────────

# Prevent overlapping runs
if [ -f "$LOCK_FILE" ]; then
    LOCK_PID=$(/bin/cat "$LOCK_FILE" 2>/dev/null)
    if kill -0 "$LOCK_PID" 2>/dev/null; then
        log "SKIP: Another sync is already running (PID $LOCK_PID)"
        exit 0
    else
        log "INFO: Stale lock file found, removing"
        /bin/rm -f "$LOCK_FILE"
    fi
fi
/bin/echo $$ > "$LOCK_FILE"

# Check if on home network
LOCAL_IP=$(/usr/sbin/ipconfig getifaddr en0 2>/dev/null || /usr/sbin/ipconfig getifaddr en1 2>/dev/null || /bin/echo "none")
if [[ "$LOCAL_IP" != ${HOME_NETWORK_PREFIX}* ]]; then
    log "SKIP: Not on home network (IP: $LOCAL_IP)"
    exit 0
fi

# Check if Mac Studio is reachable via SSH
if ! /usr/bin/ssh -o ConnectTimeout=5 -o BatchMode=yes "$STUDIO_HOST" "echo ok" &>/dev/null; then
    log "SKIP: Mac Studio not reachable via SSH"
    exit 0
fi

log "START: Syncing from Mac Studio ($LOCAL_IP)"

# ── Phase 0: Reverse push (safety net) ────────────────────────
# Before pulling from Studio, push any newer MacBook files TO the Studio.
# This prevents --delete from wiping work done on the MacBook.
# Uses --update (only copy newer files) and NO --delete.
REVERSE_OPTS=(
    --archive
    --compress
    --update            # only overwrite if MacBook file is newer
    --partial
    --human-readable
    --quiet
    --itemize-changes   # one stdout line per file actually transferred (used for change detection)
)

log "  REVERSE: Pushing newer MacBook files to Studio before pull..."
REV_OUT=""
if REV_OUT=$(/usr/bin/rsync "${REVERSE_OPTS[@]}" \
    --exclude-from="$EXCLUDE_FILE" \
    --exclude=".claude-mem/" \
    "$HOME/Development/" "${STUDIO_HOST}:Development/"); then
    n=$(count_changes "$REV_OUT")
    if [ "$n" -gt 0 ]; then
        log "  REVERSE OK: Pushed $n newer MacBook Development item(s) to Studio"
        CHANGES=$((CHANGES + n))
    else
        log "  REVERSE OK: Studio already has latest Development files"
    fi
else
    log "  REVERSE FAIL: Could not push MacBook Development files (exit code $?) — continuing with pull"
fi

# Claude Code session transcripts: push newer MacBook sessions to the Studio BEFORE
# the destructive pull. Combined with projects/ being excluded from --delete, this
# guarantees a session started on either machine can never be deleted by a sync.
REV_OUT=""
if REV_OUT=$(/usr/bin/rsync "${REVERSE_OPTS[@]}" \
    --exclude="*/sessions/" \
    "$HOME/.claude/projects/" "${STUDIO_HOST}:.claude/projects/"); then
    n=$(count_changes "$REV_OUT")
    if [ "$n" -gt 0 ]; then
        log "  REVERSE OK: Pushed $n newer MacBook Claude session item(s) to Studio"
        CHANGES=$((CHANGES + n))
    else
        log "  REVERSE OK: Studio already has latest Claude sessions"
    fi
else
    log "  REVERSE FAIL: Could not push MacBook Claude sessions (exit code $?) — continuing with pull"
fi

# ── Obsidian Uploads (disabled by default in public build) ─────────────
# This block helps sync content from an Obsidian vault that is too large
# for the paid Obsidian Sync service, or could be expanded to sync an
# entire vault. It's disabled here so the public build has no Obsidian
# dependency. To enable: (1) set UPLOADS_PATH to your vault's folder,
# (2) remove the two lines that bracket this block:
#     : <<'OBSIDIAN_DISABLED'   (this line, opener)
#     OBSIDIAN_DISABLED         (the matching closer below)
: <<'OBSIDIAN_DISABLED'
# Obsidian Uploads reverse: have Studio pull from MacBook (bypasses local TCC).
# Itemize output is generated by rsync running on the Studio and travels back over SSH stdout.
REV_OUT=""
if REV_OUT=$(/usr/bin/ssh -o ConnectTimeout=5 -o BatchMode=yes "$STUDIO_HOST" \
    "/usr/bin/rsync --archive --compress --update --partial --human-readable --quiet --itemize-changes \
    'mac-secondary:Documents/Obsidian/YOUR_VAULT/Uploads/' '$HOME/Documents/Obsidian/YOUR_VAULT/Uploads/'" 2>>"$LOG_FILE"); then
    n=$(count_changes "$REV_OUT")
    if [ "$n" -gt 0 ]; then
        log "  REVERSE OK: Pushed $n newer MacBook Obsidian Upload(s) to Studio"
        CHANGES=$((CHANGES + n))
    else
        log "  REVERSE OK: Studio already has latest Obsidian Uploads"
    fi
else
    log "  REVERSE FAIL: Could not push MacBook Obsidian Uploads (exit code $?) — continuing with pull"
fi
OBSIDIAN_DISABLED

REV_OUT=""
if REV_OUT=$(/usr/bin/rsync "${REVERSE_OPTS[@]}" \
    "$HOME/.claude/skills/" "${STUDIO_HOST}:.claude/skills/"); then
    n=$(count_changes "$REV_OUT")
    if [ "$n" -gt 0 ]; then
        log "  REVERSE OK: Pushed $n newer MacBook Claude Code skill item(s) to Studio"
        CHANGES=$((CHANGES + n))
    else
        log "  REVERSE OK: Studio already has latest Claude Code skills"
    fi
else
    log "  REVERSE FAIL: Could not push MacBook Claude Code skills (exit code $?) — continuing with pull"
fi

# ── Rsync helper ───────────────────────────────────────────────
RSYNC_OPTS=(
    --archive           # preserve permissions, symlinks, timestamps, etc.
    --compress          # compress during transfer
    --delete            # remove files on MacBook that no longer exist on Studio
    --partial           # keep partially transferred files (resume on next run)
    --human-readable
    --quiet             # keep logs clean; remove this for debugging
    --itemize-changes   # one stdout line per file actually transferred (used for change detection)
)

sync_path() {
    local remote_path="$1"
    local local_path="$2"
    shift 2
    local extra_opts=("$@")

    # Ensure local directory exists
    /bin/mkdir -p "$local_path"

    # Escape spaces for the remote shell
    local escaped_remote="${remote_path// /\\ }"

    log "  Syncing: $remote_path → $local_path"
    local rsync_output
    if rsync_output=$(/usr/bin/rsync "${RSYNC_OPTS[@]}" "${extra_opts[@]}" \
        "${STUDIO_HOST}:${escaped_remote}" "$local_path"); then
        local n=$(count_changes "$rsync_output")
        if [ "$n" -gt 0 ]; then
            log "  OK: $remote_path ($n changed)"
            CHANGES=$((CHANGES + n))
        else
            log "  OK: $remote_path (no changes)"
        fi
    else
        log "  FAIL: $remote_path (exit code $?)"
        SYNC_ERRORS=$((SYNC_ERRORS + 1))
    fi
}

sync_file() {
    local remote_path="$1"
    local local_path="$2"

    local local_dir="$(/usr/bin/dirname "$local_path")"
    /bin/mkdir -p "$local_dir"

    # Escape spaces for the remote shell
    local escaped_remote="${remote_path// /\\ }"

    log "  Syncing file: $remote_path → $local_path"
    local rsync_output
    if rsync_output=$(/usr/bin/rsync "${RSYNC_OPTS[@]}" "${STUDIO_HOST}:${escaped_remote}" "$local_path"); then
        local n=$(count_changes "$rsync_output")
        if [ "$n" -gt 0 ]; then
            log "  OK: $remote_path ($n changed)"
            CHANGES=$((CHANGES + n))
        else
            log "  OK: $remote_path (no changes)"
        fi
    else
        log "  FAIL: $remote_path (exit code $?)"
        SYNC_ERRORS=$((SYNC_ERRORS + 1))
    fi
}

# ── SQLite safe-copy helper ──────────────────────────────────
# SQLite databases consist of .db + .db-wal + .db-shm as a coherent unit.
# Rsyncing the .db alone (without WAL) produces a corrupt copy.
# Fix: use sqlite3's .backup command on the source to create a consistent snapshot,
# then rsync that snapshot instead of the live database.
safe_sync_sqlite() {
    local remote_host="$1"
    local db_path="$2"              # e.g. ~/.claude-mem/claude-mem.db
    local local_dir="$3"            # e.g. ~/.claude-mem/
    local db_name="$(/usr/bin/basename "$db_path")"
    local backup_name="${db_name}.sync-backup"

    log "  Creating safe SQLite backup on $remote_host: $db_path"

    # Create a consistent backup on the remote using sqlite3 .backup
    if /usr/bin/ssh -o ConnectTimeout=5 -o BatchMode=yes "$remote_host" \
        "if [ -f '$db_path' ]; then /usr/bin/sqlite3 '$db_path' '.backup ${db_path}.sync-backup' 2>/dev/null && echo OK; else echo MISSING; fi" 2>/dev/null | grep -q "OK"; then

        # Rsync the backup to local, then rename to the real name
        if /usr/bin/rsync --compress --quiet \
            "${remote_host}:${db_path}.sync-backup" "${local_dir}${backup_name}" 2>/dev/null; then
            /bin/mv "${local_dir}${backup_name}" "${local_dir}${db_name}"
            log "  OK: $db_name synced via safe backup"
        else
            log "  FAIL: Could not rsync $backup_name"
            SYNC_ERRORS=$((SYNC_ERRORS + 1))
        fi

        # Clean up remote backup
        /usr/bin/ssh -o BatchMode=yes "$remote_host" "/bin/rm -f '${db_path}.sync-backup'" 2>/dev/null || true
    else
        log "  SKIP: $db_path not found or sqlite3 backup failed on $remote_host"
    fi
}

# ── Merge helper ──────────────────────────────────────────────
# Merges two JSONL history files by deduplicating exact lines and sorting by timestamp.
# Result: union of both machines' session entries, ordered chronologically.
merge_history() {
    local remote_host="$1"
    local history_file="$HOME/.claude/history.jsonl"
    local tmp_remote="/tmp/studio-sync-remote-history.jsonl"
    local tmp_merged="/tmp/studio-sync-merged-history.jsonl"

    log "  Merging history.jsonl from $remote_host..."

    # Fetch remote copy
    if ! /usr/bin/rsync --compress --quiet "${remote_host}:${history_file}" "$tmp_remote" 2>/dev/null; then
        log "  SKIP: Could not fetch remote history.jsonl"
        return 0
    fi

    # Merge: deduplicate exact lines, sort by timestamp
    if /usr/bin/python3 -c "
import json, sys

seen = set()
entries = []
for path in sys.argv[1:]:
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and line not in seen:
                    seen.add(line)
                    try:
                        entries.append((json.loads(line).get('timestamp', 0), line))
                    except json.JSONDecodeError:
                        entries.append((0, line))
    except FileNotFoundError:
        pass

entries.sort(key=lambda x: x[0])
for _, line in entries:
    print(line)
" "$history_file" "$tmp_remote" > "$tmp_merged" 2>/dev/null; then
        # Only replace + count as a change if the merged result actually differs
        # from what's already on disk (otherwise we'd notify on every run).
        if [ ! -f "$history_file" ] || ! /usr/bin/cmp -s "$tmp_merged" "$history_file"; then
            /bin/mv "$tmp_merged" "$history_file"
            log "  OK: history.jsonl merged (new entries from $remote_host)"
            CHANGES=$((CHANGES + 1))
        else
            log "  OK: history.jsonl already up to date"
        fi
    else
        log "  FAIL: history.jsonl merge failed"
    fi

    /bin/rm -f "$tmp_remote" "$tmp_merged"
}

# ── Sync categories ───────────────────────────────────────────

# 0. Merge Claude Code session history (both machines write to this file)
merge_history "$STUDIO_HOST"

# 1. Claude Code configuration (~/.claude/)
#    Sync: settings, skills, plugins, plans, memory, project CLAUDE.md files
#    Skip: conversation history, debug logs, telemetry, caches (~4GB saved)
sync_path "$HOME/.claude/" "$HOME/.claude/" \
    --exclude="history.jsonl" \
    --exclude="statsig-cache/" \
    --exclude="statsig/" \
    --exclude="stats-cache.json" \
    --exclude="debug/" \
    --exclude="telemetry/" \
    --exclude="paste-cache/" \
    --exclude="shell-snapshots/" \
    --exclude="file-history/" \
    --exclude="session-env/" \
    --exclude="cache/" \
    --exclude="projects/"

# 1b. Claude Code session transcripts (~/.claude/projects/) — NON-DESTRUCTIVE.
#     Excluded from the --delete sync above so a session that exists on only one
#     machine is never deleted (this is how the "saved-jobs" session was lost).
#     --update copies only newer transcripts; the matching reverse push happens in
#     Phase 0 so MacBook-only sessions reach the Studio before anything else runs.
PROJ_OUT=""
if PROJ_OUT=$(/usr/bin/rsync "${REVERSE_OPTS[@]}" \
    --exclude="*/sessions/" \
    "${STUDIO_HOST}:.claude/projects/" "$HOME/.claude/projects/"); then
    n=$(count_changes "$PROJ_OUT")
    if [ "$n" -gt 0 ]; then
        log "  OK: ~/.claude/projects/ ($n session item(s) updated from Studio)"
        CHANGES=$((CHANGES + n))
    else
        log "  OK: ~/.claude/projects/ (no changes)"
    fi
else
    log "  FAIL: ~/.claude/projects/ pull (exit code $?)"
    SYNC_ERRORS=$((SYNC_ERRORS + 1))
fi

# 2. Claude-mem MCP plugin data — REMOVED
#    Syncing claude-mem between machines kept corrupting the database and
#    breaking Claude Code on the MacBook. Each machine now keeps its own copy.

# 3. Shared agent skills (~/.agents/)
sync_path "$HOME/.agents/" "$HOME/.agents/"

# 4. Claude Desktop config files only
#    Skip: Electron runtime caches, VMs, databases (~9GB saved)
sync_path "$HOME/Library/Application Support/Claude/" "$HOME/Library/Application Support/Claude/" \
    --include="claude_desktop_config.json" \
    --include="config.json" \
    --include="extensions-blocklist.json" \
    --include="git-worktrees.json" \
    --include="window-state.json" \
    --exclude="*"

# 5. Docker MCP configuration (~/.docker/mcp/)
sync_path "$HOME/.docker/mcp/" "$HOME/.docker/mcp/" \
    --exclude="mcp-toolkit.db"

# ── Obsidian Uploads (disabled by default in public build) ─────────────
# This block helps sync content from an Obsidian vault that is too large
# for the paid Obsidian Sync service, or could be expanded to sync an
# entire vault. It's disabled here so the public build has no Obsidian
# dependency. To enable: (1) set UPLOADS_PATH to your vault's folder,
# (2) remove the two lines that bracket this block:
#     : <<'OBSIDIAN_DISABLED'   (this line, opener)
#     OBSIDIAN_DISABLED         (the matching closer below)
: <<'OBSIDIAN_DISABLED'
# 6. Obsidian Uploads (files too large for Obsidian Sync)
#    macOS TCC blocks LaunchAgent-spawned processes from modifying files in
#    ~/Documents/, even with FDA on a wrapper .app. Workaround: SSH to Studio
#    and have it rsync push to MacBook. Files arrive via sshd, which writes
#    with the user's full permissions and bypasses TCC.
UPLOADS_PATH="Documents/Obsidian/YOUR_VAULT/Uploads"
log "  Syncing: $HOME/$UPLOADS_PATH (via Studio push)"
UPLOADS_OUT=""
if UPLOADS_OUT=$(/usr/bin/ssh -o ConnectTimeout=5 -o BatchMode=yes "$STUDIO_HOST" \
    "/usr/bin/rsync --archive --compress --partial --human-readable --quiet --itemize-changes \
    '$HOME/$UPLOADS_PATH/' 'mac-secondary:$UPLOADS_PATH/'" 2>>"$LOG_FILE"); then
    n=$(count_changes "$UPLOADS_OUT")
    if [ "$n" -gt 0 ]; then
        log "  OK: $HOME/$UPLOADS_PATH ($n changed)"
        CHANGES=$((CHANGES + n))
    else
        log "  OK: $HOME/$UPLOADS_PATH (no changes)"
    fi
else
    log "  FAIL: $HOME/$UPLOADS_PATH (exit code $?)"
    SYNC_ERRORS=$((SYNC_ERRORS + 1))
fi
OBSIDIAN_DISABLED

# 7. Development directory (big one — uses exclude file)
sync_path "$HOME/Development/" "$HOME/Development/" \
    --exclude-from="$EXCLUDE_FILE"

# 8. Shell config
sync_file "$HOME/.zshrc" "$HOME/.zshrc"

# 9. Git config
sync_file "$HOME/.gitconfig" "$HOME/.gitconfig"

# 10. Environment LaunchAgent
sync_file "$HOME/Library/LaunchAgents/com.YOUR_USERNAME.env.plist" \
    "$HOME/Library/LaunchAgents/com.YOUR_USERNAME.env.plist"

# ── Wrap up ────────────────────────────────────────────────────
# Only fire a toast when something actually happened (files changed or errored).
# A clean no-op run logs only — no notification noise.
if [ "$SYNC_ERRORS" -gt 0 ]; then
    log "DONE: Sync completed with $SYNC_ERRORS errors ($CHANGES changes)"
    notify "Sync finished with $SYNC_ERRORS errors — check log"
elif [ "$CHANGES" -gt 0 ]; then
    log "DONE: Sync completed successfully ($CHANGES changes)"
    notify "Sync complete — $CHANGES item(s) updated"
else
    log "DONE: Sync completed successfully (no changes)"
fi
